"""Bounded categorical scaling and loglinear procedures (Torch-free manifest)."""

ESTIMATORS = ()
_P = "openecon.econometrics.categorical"
EXPORTS = {
    "catreg_spline": f"{_P}.spline_regression:catreg_spline",
    "catreg_mspline": f"{_P}.spline_regression:catreg_mspline",
    "catreg_spline_predict": f"{_P}.spline_regression:catreg_spline_predict",
    "catpca_spline": f"{_P}.spline_pca:catpca_spline",
    "catpca_mspline": f"{_P}.spline_pca:catpca_mspline",
    "catpca_spline_predict": f"{_P}.spline_pca:catpca_spline_predict",
    "catpca_varimax_fweight": f"{_P}.frequency_rotation:catpca_varimax_fweight",
    "catpca_promax_fweight": f"{_P}.frequency_rotation:catpca_promax_fweight",
    "catpca_rotated_predict_fweight": f"{_P}.frequency_rotation:catpca_rotated_predict_fweight",
    "catreg_nominal_fweight_bootstrap": f"{_P}.frequency_bootstrap:catreg_nominal_fweight_bootstrap",
    "catreg_ordinal_fweight_bootstrap": f"{_P}.frequency_bootstrap:catreg_ordinal_fweight_bootstrap",
    "catreg_fweight_bootstrap_restore": f"{_P}.frequency_bootstrap:catreg_fweight_bootstrap_restore",
    "catreg_nominal_fweight": f"{_P}.frequency_regression:catreg_nominal_fweight",
    "catreg_ordinal_fweight": f"{_P}.frequency_regression:catreg_ordinal_fweight",
    "catreg_nominal_response_fweight": f"{_P}.frequency_regression:catreg_nominal_response_fweight",
    "catreg_ordinal_response_fweight": f"{_P}.frequency_regression:catreg_ordinal_response_fweight",
    "catreg_fweight_predict": f"{_P}.frequency_regression:catreg_fweight_predict",
    "catpca_fweight": f"{_P}.frequency_pca:catpca_fweight",
    "catpca_fweight_predict": f"{_P}.frequency_pca:catpca_fweight_predict",
    "catpca_category_centroids": f"{_P}.frequency_pca:catpca_category_centroids",
    "mca_fweight": f"{_P}.frequency_scaling:mca_fweight",
    "mca_fweight_project": f"{_P}.frequency_scaling:mca_fweight_project",
    "overals_fweight": f"{_P}.frequency_scaling:overals_fweight",
    "catreg_nominal": f"{_P}.optimal:catreg_nominal",
    "catreg_ordinal": f"{_P}.optimal:catreg_ordinal",
    "catreg_predict": f"{_P}.optimal:catreg_predict",
    "catpca_predict": f"{_P}.optimal:catpca_predict",
    "catpca": f"{_P}.optimal:catpca",
    "mca": f"{_P}.scaling:mca",
    "mca_project": f"{_P}.scaling:mca_project",
    "overals": f"{_P}.scaling:overals",
    "mds_nonmetric": f"{_P}.scaling:mds_nonmetric",
    "loglinear_ipf": f"{_P}.loglinear:loglinear_ipf",
    "loglinear_ml": f"{_P}.loglinear:loglinear_ml",
    "loglinear_compare": f"{_P}.loglinear:loglinear_compare",
    "catreg_nominal_response": f"{_P}.optimal_options:catreg_nominal_response",
    "catreg_ordinal_response": f"{_P}.optimal_options:catreg_ordinal_response",
    "catreg_outcome_predict": f"{_P}.optimal_options:catreg_outcome_predict",
    "catreg_bootstrap": f"{_P}.optimal_options:catreg_bootstrap",
    "catpca_varimax": f"{_P}.rotation:catpca_varimax",
    "catpca_promax": f"{_P}.rotation:catpca_promax",
    "catpca_rotated_predict": f"{_P}.rotation:catpca_rotated_predict",
    "loglinear_multinomial": f"{_P}.sampling:loglinear_multinomial",
    "loglinear_product_multinomial": f"{_P}.sampling:loglinear_product_multinomial",
    "loglinear_sampling_compare": f"{_P}.sampling:loglinear_sampling_compare",
    "loglinear_select": f"{_P}.selection:loglinear_select",
}
