"""Local UI acceptance for physical fixtures generated by the native matrix.

Set OPENECON_NATIVE_MATRIX_MANIFEST to the writer's captured.json. These are
seeded development fixtures and a bounded acceptance example, not customer data.
"""
import hashlib
import json
import os
from pathlib import Path
import sys

import openecon as oe
import pandas as pd
import torch

display = globals().get("display", print)
torch.set_num_threads(2)

manifest = Path(os.environ.get("OPENECON_NATIVE_MATRIX_MANIFEST", "native_matrix_cases/captured.json"))
cases = {case["model"]: case for case in json.loads(manifest.read_text())["cases"]}
names = ["ols", "betareg", "ivprobit", "teffects", "var", "mixed"]
results = {}
proof = []
for name in names:
    case = cases[name]
    source = Path(case["path"])
    with source.open("rb") as stream:
        before = hashlib.file_digest(stream, "sha256").hexdigest()
    assert before == case["source_sha256"]
    dataset = oe.scan(source)
    dataset._metadata = case.get("metadata", {})
    result = oe.fit(oe.ModelSpec.model_validate(case["spec"]), data=dataset)
    restored = oe.ResultBundle.model_validate_json(result.model_dump_json())
    assert restored.model_dump() == result.model_dump()
    with source.open("rb") as stream:
        after = hashlib.file_digest(stream, "sha256").hexdigest()
    assert after == before
    results[name] = restored
    proof.append({"model": name, "rows": case["rows"], "nobs": result.nobs,
                  "source_unchanged": True, "full_saved_result_equal": True})
    display(restored)

ols_source = Path(cases["ols"]["path"])
evaluation = pd.read_csv(ols_source).dropna().head(9)
display(oe.predict(results["ols"], data=evaluation, interval="mean"))
var_source = Path(cases["var"]["path"])
future = pd.read_parquet(var_source).dropna().head(3)
display(oe.forecast(results["var"], 3, exog=future))
terms = [coefficient.term for coefficient in results["ols"].coefficients]
display(pd.DataFrame(results["ols"].covariance_matrix, columns=terms, index=terms))
print("NATIVE_MATRIX_UI:" + json.dumps({
    "cases": proof, "outputs": 9, "frozen": getattr(sys, "frozen", False),
    "sdk_from_bundle": hasattr(sys, "_MEIPASS") and str(oe.__file__).startswith(str(sys._MEIPASS)),
    "no_scipy_loaded": not any(name == "scipy" or name.startswith("scipy.") for name in sys.modules),
    "scope": "Six representative physical cases, saved full results, external mean inference and saved VAR forecast"}))
