"""Cointegrating regressions; this manifest does not import numerical packages."""

from openecon.econometrics.registry import EstimatorInfo, Option

OPTIONS = (
    Option("trend", "str", "c", choices=("n", "c", "ct", "ctt")),
    Option("kernel", "str", "bartlett", choices=("bartlett", "parzen", "quadratic_spectral")),
    Option(
        "bandwidth",
        "int",
        4,
        minimum=0,
        doc="Fixed kernel bandwidth; automatic bandwidth selection is not implied.",
    ),
    Option("df_adjust", "bool", False),
    Option("leads", "int", 0, minimum=0, maximum=100),
    Option("lags", "int", 0, minimum=0, maximum=100),
    Option("selection", "str", "fixed", choices=("fixed", "aic", "bic", "hqic")),
    Option("max_leads", "int", 4, minimum=0, maximum=100),
    Option("max_lags", "int", 4, minimum=0, maximum=100),
)
ESTIMATORS = (
    EstimatorInfo(
        name="fmols",
        title="Fully modified OLS",
        family="longrun",
        entry="openecon.econometrics.longrun.models:fit_longrun",
        function="fmols",
        covariances=("nonrobust",),
        default_covariance="nonrobust",
        categorical=False,
        intercept="never",
        time="optional",
        panel="none",
        inference="z",
        options=OPTIONS + (),
        description="Fully modified OLS: explicit cointegration assumption, kernel/sample and full covariance retained.",
    ),
    EstimatorInfo(
        name="dols",
        title="Dynamic OLS",
        family="longrun",
        entry="openecon.econometrics.longrun.models:fit_longrun",
        function="dols",
        covariances=("nonrobust", "hac"),
        default_covariance="nonrobust",
        categorical=False,
        intercept="never",
        time="optional",
        panel="none",
        inference="z",
        options=OPTIONS + (),
        description="Dynamic OLS: explicit cointegration assumption, kernel/sample and full covariance retained.",
    ),
    EstimatorInfo(
        name="ccr",
        title="Canonical cointegrating regression",
        family="longrun",
        entry="openecon.econometrics.longrun.models:fit_longrun",
        function="ccr",
        covariances=("nonrobust",),
        default_covariance="nonrobust",
        categorical=False,
        intercept="never",
        time="optional",
        panel="none",
        inference="z",
        options=OPTIONS + (),
        description="Canonical cointegrating regression: explicit cointegration assumption, kernel/sample and full covariance retained.",
    ),
    EstimatorInfo(
        name="panel_fmols",
        title="Panel fully modified OLS",
        family="longrun",
        entry="openecon.econometrics.longrun.models:fit_longrun",
        function="panel_fmols",
        covariances=("nonrobust",),
        default_covariance="nonrobust",
        categorical=False,
        intercept="never",
        time="required",
        panel="required",
        inference="z",
        options=OPTIONS + (Option("pooling", "str", "pooled", choices=("pooled", "mean_group")),),
        description="Panel fully modified OLS: explicit cointegration assumption, kernel/sample and full covariance retained.",
    ),
    EstimatorInfo(
        name="panel_dols",
        title="Panel dynamic OLS",
        family="longrun",
        entry="openecon.econometrics.longrun.models:fit_longrun",
        function="panel_dols",
        covariances=("nonrobust", "hac"),
        default_covariance="nonrobust",
        categorical=False,
        intercept="never",
        time="required",
        panel="required",
        inference="z",
        options=OPTIONS + (Option("pooling", "str", "pooled", choices=("pooled", "mean_group")),),
        description="Panel dynamic OLS: explicit cointegration assumption, kernel/sample and full covariance retained.",
    ),
)
