"""Ordered logit and ordered probit by full maximum likelihood: Stata's ``ologit`` / ``oprobit``.

Model
-----
An ordered outcome with categories ``1 < 2 < ... < J`` is generated by a latent
index ``y* = x'b + offset + e`` and cutpoints ``k_1 < ... < k_{J-1}``:

    Pr(y = j | x) = F(k_j - x'b) - F(k_{j-1} - x'b),   k_0 = -inf,  k_J = +inf,

with ``F`` the logistic (``ologit``) or standard normal (``oprobit``)
distribution function. There is no constant: it is absorbed by the cutpoints,
which are estimated directly and reported as the ancillary terms ``/cut1`` ..
``/cut{J-1}`` after the slopes (Stata's parameterization).

Categories
----------
A numeric outcome is ordered by value; an ordered pandas ``Categorical`` by its
category order. The categories observed in the estimation sample define ``J``;
their labels are returned in ``extra['categories']``.

Estimation
----------
Newton-Raphson on ``(b, k)`` with the analytic score and Hessian of
``kernels.OrderedObjective``, started at ``b = 0`` and the cutpoints that
reproduce the (weighted) cumulative shares of the sample, i.e. at the
maximum of the cutpoints-only model. A trial step that would reorder the
cutpoints is rejected by the line search. The iteration runs on regressors
centred at their means (the cutpoints absorb the shift, ``cut = cut_c + m'b``)
and estimates and covariance are mapped back exactly, so a regressor with a
large level does not cost accuracy.

Reported
--------
``metrics``: log_likelihood, pseudo_r_squared (McFadden, against the
cutpoints-only model with the same offset), aic, bic (``k + J - 1``
parameters), n_categories. ``tests['model']``: LR chi2(k) against the
cutpoints-only model (``nonrobust``) or the Wald chi2(k) of the slopes.
A likelihood that keeps increasing because a regressor predicts some
categories perfectly is rejected with ``separation_detected``.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import pandas as pd
import torch
from pandas.api.types import is_bool_dtype, is_numeric_dtype
from torch import Tensor

from openecon.analysis import fit
from openecon.analysis_contracts import AnalysisError
from openecon.econometrics.core import (
    ModelFrame, build_result, column_list, information_criteria, kernel_call,
)
from openecon.econometrics.discrete.common import (
    EXTREME, EXTREME_EARLY, Separated, Weights, build_spec, centre_regressors, check_pweights,
    implicit_constant_design, json_label, likelihood_covariance, likelihood_weights, maximize,
    model_test, offset_column, optimizer_record, perfectly_predicted, pseudo_r_squared,
    raise_not_converged, reparameterize, require_observations, resolve_covariance,
    separation_watch,
)
from openecon.econometrics.discrete.kernels import OrderedObjective
from openecon.engines.covariance import group_sums
from openecon.models import ModelSpec, ResultBundle

MAX_CATEGORIES = 500
_TITLES = {"ologit": "Ordered logistic regression", "oprobit": "Ordered probit regression"}


def ordered_outcome(frame: ModelFrame, command: str) -> tuple[Tensor, list[Any]]:
    """Category codes ``0..J-1`` in outcome order and the category labels."""
    name = frame.spec.outcome
    series = frame.series(name)
    if isinstance(series.dtype, pd.CategoricalDtype):
        if not series.cat.ordered:
            raise AnalysisError(
                "invalid_ordered_outcome",
                f"{command}: the Categorical outcome '{name}' is unordered. Declare its order "
                "(for example df[name].cat.as_ordered() after setting the categories) or use "
                "oe.mlogit for unordered categories.")
        observed = series.cat.remove_unused_categories()
        labels = [json_label(value) for value in observed.cat.categories]
        codes = torch.from_numpy(observed.cat.codes.to_numpy(dtype="int64", copy=True))
    elif is_numeric_dtype(series.dtype) or is_bool_dtype(series.dtype):
        unique, codes = torch.unique(frame.numeric(name), sorted=True, return_inverse=True)
        labels = [json_label(value) for value in unique.tolist()]
    else:
        raise AnalysisError(
            "invalid_ordered_outcome",
            f"{command}: the outcome '{name}' must be numeric (categories ordered by value) or "
            "an ordered pandas Categorical.")
    if len(labels) < 2:
        raise AnalysisError("constant_outcome", f"{command}: the outcome '{name}' takes a single "
                            "value in the estimation sample; at least two categories are needed.")
    if len(labels) > MAX_CATEGORIES:
        raise AnalysisError(
            "too_many_categories",
            f"{command}: the outcome '{name}' has {len(labels)} distinct values (limit "
            f"{MAX_CATEGORIES}). An ordered model needs a small number of categories; a "
            "continuous outcome belongs in a linear model.")
    return codes, labels


def _starting_cutpoints(shares: Tensor, link: str) -> Tensor:
    """Cutpoints reproducing the cumulative category shares when ``b = 0``."""
    cumulative = torch.cumsum(shares, dim=0)[:-1].clamp(1e-12, 1 - 1e-12)
    return torch.logit(cumulative) if link == "logit" else torch.special.ndtri(cumulative)


def _null_log_likelihood(frame: ModelFrame, codes: Tensor, categories: int, weights: Weights,
                         offset: Tensor | None, link: str, start: Tensor, command: str) -> float:
    """Log likelihood of the cutpoints-only model with the same weights and offset."""
    if offset is None:
        totals = group_sums(weights.user, codes, categories)
        return float((totals * torch.log(totals / totals.sum())).sum())
    empty = torch.empty((frame.n, 0), dtype=torch.float64)
    objective = kernel_call(OrderedObjective, empty, codes, categories, weights.user, offset, link)
    result = maximize(objective, start, what=f"{command} (cutpoints-only model)",
                      scale=weights.scale)
    if not result.converged:
        raise AnalysisError("nonconvergence", f"{command}: the cutpoints-only model with the "
                            f"offset did not converge: {result.diagnostics.get('message')}")
    return result.value


def _fit(spec: ModelSpec, data: Any, link: str) -> ResultBundle:
    command = spec.estimator
    frame = ModelFrame(spec, data)
    check_pweights(frame)
    codes, labels = ordered_outcome(frame, command)
    categories = len(labels)
    weights = likelihood_weights(frame)
    offset = offset_column(frame)
    design = implicit_constant_design(frame, None, weights.for_screen())
    centre = centre_regressors(design, weights, implicit_constant=True)
    k, cuts = len(design.terms), categories - 1
    require_observations(weights.nobs, k + cuts)
    totals = group_sums(weights.user, codes, categories)
    start_cuts = _starting_cutpoints(totals / totals.sum(), link)
    objective = kernel_call(OrderedObjective, design.x, codes, categories, weights.user, offset,
                            link)
    start = torch.cat([torch.zeros(k, dtype=torch.float64), start_cuts])

    def separated(theta: Tensor, threshold: float) -> int:
        return perfectly_predicted(objective.probabilities(theta), threshold)

    try:
        result = maximize(objective, start, what=command, callback=separation_watch(separated),
                          scale=weights.scale)
    except Separated as stop:
        raise_not_converged(command, separated(stop.theta, EXTREME_EARLY),
                            "the likelihood is monotone.")
    if not result.converged:
        # Own categories predicted perfectly, or the two sides of a cutpoint separated.
        count = separated(result.theta, EXTREME) or objective.determined(result.theta, EXTREME)
        raise_not_converged(command, count, result.diagnostics.get("message"))
    centred, log_likelihood = result.theta, result.value
    covariance, info = likelihood_covariance(frame, result.hessian,
                                             lambda: objective.score_rows(centred), weights)
    # Fitted on x - m: cut_j - x'b = (cut_j - m'b) - (x - m)'b, so cut = cut_c + m'b.
    jacobian = torch.eye(k + cuts, dtype=torch.float64)
    jacobian[k:, :k] = centre
    theta, covariance = reparameterize(centred, covariance, jacobian)
    null = _null_log_likelihood(frame, codes, categories, weights, offset, link, start_cuts,
                                command)
    criteria = information_criteria(log_likelihood, k + cuts, weights.nobs)
    metrics = {"log_likelihood": log_likelihood,
               "pseudo_r_squared": pseudo_r_squared(log_likelihood, null),
               "aic": criteria["aic"], "bic": criteria["bic"], "n_categories": categories}
    tests = {"model": model_test(frame, theta, covariance, range(k), log_likelihood, null,
                                 null_model="the cutpoints-only model")}
    extra = {
        "link": link, "categories": labels, "cutpoints": theta[k:].tolist(),
        "category_counts": totals.tolist(), "null_log_likelihood": null,
        "category_order": "ordered Categorical" if isinstance(
            frame.series(spec.outcome).dtype, pd.CategoricalDtype) else "sorted numeric values",
        "parameterization": "Pr(y = j) = F(cut_j - x'b) - F(cut_{j-1} - x'b); no constant",
    }
    return build_result(
        frame, terms=[*design.terms, *(f"/cut{j}" for j in range(1, categories))],
        params=theta, covariance=covariance, equations=[spec.outcome] * k + [None] * cuts,
        use_t=False, title=_TITLES[command], metrics=metrics, nobs=weights.nobs, inference=info,
        tests=tests, extra=extra, categories=design.categories,
        solver="newton_observed_hessian",
        solver_diagnostics={"converged": True, "iterations": result.iterations},
        optimizer=optimizer_record(result))


def fit_ologit(spec: ModelSpec, data: Any) -> ResultBundle:
    """Entry point of ``ologit``: ``(spec, data) -> ResultBundle``."""
    return _fit(spec, data, "logit")


def fit_oprobit(spec: ModelSpec, data: Any) -> ResultBundle:
    """Entry point of ``oprobit``: ``(spec, data) -> ResultBundle``."""
    return _fit(spec, data, "probit")


def _ordered(estimator: str, *, data: Any, y: str, x: Sequence[str], covariance: str | None,
             cluster: str | Sequence[str] | None, weights: str | None, weight_type: str | None,
             offset: str | None, categorical: Sequence[str] | None, missing: str,
             alpha: float) -> ResultBundle:
    spec = build_spec(
        estimator, outcome=y, predictors=column_list(x, "x"),
        categorical=column_list(categorical, "categorical"), intercept=False,
        covariance=resolve_covariance(covariance, cluster, weight_type), cluster=cluster,
        weights=weights, weight_type=weight_type, missing=missing, alpha=alpha,
        columns={"offset": offset})
    return fit(spec, data=data)


def ologit(*, data: Any, y: str, x: Sequence[str], covariance: str | None = None,
           cluster: str | Sequence[str] | None = None, weights: str | None = None,
           weight_type: str | None = None, offset: str | None = None,
           categorical: Sequence[str] | None = None, missing: str = "raise",
           alpha: float = 0.05) -> ResultBundle:
    """Ordered logistic regression, Stata's ``ologit`` (SPSS PLUM, EViews ordered logit).

    Model
        For an outcome with ordered categories ``1 < ... < J``,

            ``Pr(y = j | x) = L(k_j - x'b) - L(k_{j-1} - x'b)``,  ``L(v) = 1/(1 + e^-v)``,

        with ``k_0 = -inf`` and ``k_J = +inf``. Equivalently
        ``ln[Pr(y <= j)/Pr(y > j)] = k_j - x'b`` for every ``j`` (proportional odds):
        ``exp(b)`` is the odds ratio of a higher category per unit of ``x``. There is no
        constant; the ``J - 1`` cutpoints take its place and are estimated directly.

    Estimator
        Full maximum likelihood of ``sum_i w_i ln Pr(y_i | x_i)`` over ``(b, k)`` by
        Newton-Raphson with the analytic score and Hessian, started at ``b = 0`` and the
        cutpoints matching the cumulative category shares. Convergence requires a negative
        definite Hessian and ``g'(-H)^-1 g <= 1e-10``.

    Parameters
        data: DataFrame (or mapping of columns / list of records).
        y: ordered outcome: numeric (categories ordered by value) or an ordered pandas
            ``Categorical``. The categories observed in the sample define ``J >= 2``.
        x: list of regressors. Constant or collinear columns are omitted left to right
            with a warning (a constant is collinear with the cutpoints).
        covariance: ``'nonrobust'`` (default; inverse observed information, Stata's
            ``vce(oim)``), ``'opg'``, ``'robust'`` (``N/(N-1)`` sandwich), ``'cluster'``
            (``G/(G-1)`` sandwich; implied when ``cluster`` is given; two columns give
            two-way clustering).
        cluster: cluster column, or a list of two columns.
        weights, weight_type: ``'fweight'`` (replicates rows, ``N = sum w``), ``'aweight'``
            (rescaled to sum to N), ``'pweight'`` (robust covariance by default),
            ``'iweight'`` (as given).
        offset: column added to ``x'b`` with coefficient 1.
        categorical: regressors to expand into treatment-coded indicators (first level
            omitted), named ``name[level]``.
        missing: ``'raise'`` (default) or ``'drop'`` incomplete rows.
        alpha: significance level of the confidence intervals.

    Result
        z statistics. Terms: the slopes (equation = the outcome), then ``/cut1`` ..
        ``/cut{J-1}``. ``metrics``: log_likelihood, pseudo_r_squared (``1 - ll/ll_0``,
        ``ll_0`` the cutpoints-only model), aic, bic (``k + J - 1`` parameters),
        n_categories. ``tests['model']``: LR chi2(k) against the cutpoints-only model
        (``nonrobust``) or Wald chi2(k) of the slopes. ``extra``: ``categories`` (labels
        in order), ``cutpoints``, ``category_counts``, ``null_log_likelihood``.
        Perfect prediction of some categories raises ``separation_detected``.

    Stata
        ``ologit rep77 foreign length mpg, vce(cluster make_id)`` is
        ``oe.ologit(data=df, y='rep77', x=['foreign', 'length', 'mpg'], cluster='make_id')``.

    Example
        >>> import numpy as np, pandas as pd, openecon as oe
        >>> rng = np.random.default_rng(0)
        >>> df = pd.DataFrame({"x": rng.normal(size=800)})
        >>> latent = 0.8 * df.x + rng.logistic(size=800)
        >>> df["rating"] = np.digitize(latent, [-1.0, 0.5, 2.0])      # categories 0..3
        >>> print(oe.ologit(data=df, y="rating", x=["x"]).summary())
    """
    return _ordered("ologit", data=data, y=y, x=x, covariance=covariance, cluster=cluster,
                    weights=weights, weight_type=weight_type, offset=offset,
                    categorical=categorical, missing=missing, alpha=alpha)


def oprobit(*, data: Any, y: str, x: Sequence[str], covariance: str | None = None,
            cluster: str | Sequence[str] | None = None, weights: str | None = None,
            weight_type: str | None = None, offset: str | None = None,
            categorical: Sequence[str] | None = None, missing: str = "raise",
            alpha: float = 0.05) -> ResultBundle:
    """Ordered probit regression, Stata's ``oprobit`` (SPSS PLUM probit link, EViews ordered).

    Model
        A latent ``y* = x'b + e`` with ``e ~ N(0, 1)`` is observed in ordered categories:
        ``y = j`` when ``k_{j-1} < y* <= k_j``, so

            ``Pr(y = j | x) = Phi(k_j - x'b) - Phi(k_{j-1} - x'b)``,

        ``k_0 = -inf``, ``k_J = +inf``. There is no constant; the ``J - 1`` cutpoints are
        estimated directly (Stata's parameterization). Coefficients are in units of the
        latent standard deviation.

    Estimator
        Full maximum likelihood by Newton-Raphson with the analytic score and Hessian,
        started at ``b = 0`` and the cutpoints matching the cumulative category shares.
        Interval probabilities are computed on the side where both normal tails are
        small, so the likelihood stays accurate for extreme indices.

    Parameters
        Exactly as :func:`ologit`: ``data``, ``y`` (numeric or ordered Categorical),
        ``x``, ``covariance`` (``'nonrobust'``, ``'opg'``, ``'robust'``, ``'cluster'``),
        ``cluster``, ``weights`` / ``weight_type`` (``fweight``, ``aweight``, ``pweight``,
        ``iweight``), ``offset``, ``categorical``, ``missing``, ``alpha``.

    Result
        As :func:`ologit`: slopes then ``/cut1`` .. ``/cut{J-1}`` with z statistics;
        ``metrics`` log_likelihood, pseudo_r_squared, aic, bic, n_categories;
        ``tests['model']`` LR chi2(k) (``nonrobust``) or Wald chi2(k);
        ``extra['categories']``, ``extra['cutpoints']``.

    Stata
        ``oprobit rep77 foreign length mpg [fweight=n]`` is
        ``oe.oprobit(data=df, y='rep77', x=['foreign', 'length', 'mpg'], weights='n',
        weight_type='fweight')``.

    Example
        >>> import numpy as np, pandas as pd, openecon as oe
        >>> rng = np.random.default_rng(0)
        >>> df = pd.DataFrame({"x": rng.normal(size=800)})
        >>> df["rating"] = np.digitize(0.6 * df.x + rng.normal(size=800), [-0.5, 0.7])
        >>> print(oe.oprobit(data=df, y="rating", x=["x"], covariance="robust").summary())
    """
    return _ordered("oprobit", data=data, y=y, x=x, covariance=covariance, cluster=cluster,
                    weights=weights, weight_type=weight_type, offset=offset,
                    categorical=categorical, missing=missing, alpha=alpha)
