"""Bounded balance, sensitivity and design-identified treatment targets; Torch-free manifest."""

ESTIMATORS = ()
_PACKAGE = "openecon.econometrics.causal_design"
EXPORTS = {
    "ebalance": f"{_PACKAGE}.balance:ebalance",
    "cem": f"{_PACKAGE}.balance:cem",
    "balance": f"{_PACKAGE}.balance:balance",
    "rosenbaum_bounds": f"{_PACKAGE}.paired:rosenbaum_bounds",
    "paired_randomization": f"{_PACKAGE}.paired:paired_randomization",
    "treatment_cdf": f"{_PACKAGE}.distribution:treatment_cdf",
    "treatment_quantile": f"{_PACKAGE}.distribution:treatment_quantile",
    "treatment_rmst": f"{_PACKAGE}.survival:treatment_rmst",
    "ovb_sensitivity": f"{_PACKAGE}.ovb:ovb_sensitivity",
    "evalue": f"{_PACKAGE}.partial_identification:evalue",
    "manski_ate": f"{_PACKAGE}.partial_identification:manski_ate",
    "lee_bounds": f"{_PACKAGE}.partial_identification:lee_bounds",
    "randomization_test": f"{_PACKAGE}.randomization:randomization_test",
    "stratified_randomization": f"{_PACKAGE}.randomization:stratified_randomization",
    "rosenbaum_rank_bounds": f"{_PACKAGE}.randomization:rosenbaum_rank_bounds",
    "bias_sensitivity": f"{_PACKAGE}.bias:bias_sensitivity",
    "ovb_benchmark": f"{_PACKAGE}.ovb_postest:ovb_benchmark",
    "ovb_robustness": f"{_PACKAGE}.ovb_postest:ovb_robustness",
    "treatment_cdf_ipw": f"{_PACKAGE}.observational_distribution:treatment_cdf_ipw",
    "treatment_quantile_ipw": f"{_PACKAGE}.observational_distribution:treatment_quantile_ipw",
    "treatment_cdf_aipw": f"{_PACKAGE}.observational_distribution:treatment_cdf_aipw",
    "treatment_survival_ipcw": f"{_PACKAGE}.observational_survival:treatment_survival_ipcw",
    "treatment_rmst_ipcw": f"{_PACKAGE}.observational_survival:treatment_rmst_ipcw",
    "treatment_rmst_aipw": f"{_PACKAGE}.observational_survival:treatment_rmst_aipw",
    "cluster_randomization": f"{_PACKAGE}.assignment_extensions:cluster_randomization",
    "bernoulli_randomization": f"{_PACKAGE}.assignment_extensions:bernoulli_randomization",
    "neyman_ate": f"{_PACKAGE}.neyman:neyman_ate",
    "stratified_neyman_ate": f"{_PACKAGE}.neyman:stratified_neyman_ate",
    "cluster_neyman_ate": f"{_PACKAGE}.neyman:cluster_neyman_ate",
    "paired_neyman_ate": f"{_PACKAGE}.neyman:paired_neyman_ate",
    "manski_ate_inference": f"{_PACKAGE}.identification_extensions:manski_ate_inference",
    "stratified_lee_bounds": f"{_PACKAGE}.identification_extensions:stratified_lee_bounds",
    "randomization_confidence_set": f"{_PACKAGE}.confidence_sets:randomization_confidence_set",
    "paired_randomization_confidence_set": f"{_PACKAGE}.confidence_sets:paired_randomization_confidence_set",
    "cluster_randomization_confidence_set": f"{_PACKAGE}.confidence_sets:cluster_randomization_confidence_set",
    "bernoulli_neyman_ate": f"{_PACKAGE}.multiarm_neyman:bernoulli_neyman_ate",
    "multiarm_neyman_ate": f"{_PACKAGE}.multiarm_neyman:multiarm_neyman_ate",
    "stratified_multiarm_neyman_ate": f"{_PACKAGE}.multiarm_neyman:stratified_multiarm_neyman_ate",
    "treatment_effect_cdf_bounds": f"{_PACKAGE}.effect_distribution:treatment_effect_cdf_bounds",
    "treatment_effect_quantile_bounds": f"{_PACKAGE}.effect_distribution:treatment_effect_quantile_bounds",
    "causal_design_save": f"{_PACKAGE}.common:causal_design_save",
    "causal_design_load": f"{_PACKAGE}.common:causal_design_load",
}
