"""Generate deterministic, source-backed current scope; --check refuses drift."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
JSON_PATH = ROOT / "docs/econometrics/capabilities.generated.json"
MD_PATH = ROOT / "docs/capabilities.md"


def snapshot(source_ref: str) -> dict:
    from openecon.analysis_contracts import capabilities

    cap = capabilities()
    source_files = sorted(
        {
            "src/openecon/analysis_contracts.py",
            "src/openecon/dataset.py",
            "src/openecon/dataset_prepare.py",
            "src/openecon/source_readers.py",
            "src/openecon/prediction_capabilities.py",
            "src/openecon/econometrics/registry.py",
            "src/openecon/econometrics/streaming_registry.py",
            "src/openecon/linear_ols/spec.py",
            "src/openecon/resources.py",
            "src/openecon/engines/separation.py",
            "pyproject.toml",
            "desktop/src-tauri/tauri.conf.json",
            "packages/openecon-charts/pyproject.toml",
            *[
                str(path.relative_to(ROOT))
                for path in (ROOT / "src/openecon/econometrics").glob("*/__init__.py")
            ],
        }
    )
    project = tomllib.loads((ROOT / "pyproject.toml").read_text())
    charts = tomllib.loads((ROOT / "packages/openecon-charts/pyproject.toml").read_text())
    native = json.loads((ROOT / "desktop/src-tauri/tauri.conf.json").read_text())
    return {
        "schema": 1,
        "source_ref": source_ref,
        "source_fingerprints": {
            name: hashlib.sha256((ROOT / name).read_bytes()).hexdigest() for name in source_files
        },
        "versions": {
            "sdk": project["project"]["version"],
            "native": native["version"],
            "charts": charts["project"]["version"],
        },
        "estimators": cap["estimators"],
        "families": cap["families"],
        "streaming": cap["streaming"],
        "postestimation": cap["postestimation"],
        "execution": cap["execution"],
        "precision": cap["precision"],
        "input": cap["input"],
        "dataset_preparation": cap["dataset_preparation"],
        "workspace": cap["workspace"],
        "stata_parity_validated": cap["stata_parity_validated"],
        "cuda_hardware_validated": cap["network"]["cuda_hardware_validated"],
        "dependencies": {
            "runtime": project["project"]["dependencies"],
            "optional": project["project"]["optional-dependencies"],
            "dev_oracles": project["dependency-groups"]["dev"],
        },
    }


def markdown(value: dict) -> str:
    estimates = value["estimators"]
    replay = value["streaming"]
    prediction = value["postestimation"]["saved_prediction"]
    versions = value["versions"]
    lines = [
        "# Current OpenEconometrics capability inventory",
        "",
        "Generated by `scripts/generate_capability_docs.py`; check with `--check`. "
        "The JSON companion retains complete options, conditions and resource contracts.",
        "",
        f"Source reference: `{value['source_ref']}`. Content fingerprints in "
        "[the generated inventory](econometrics/capabilities.generated.json) identify the exact metadata used. "
        "The reference is a source snapshot, not an installation or public-release claim.",
        "",
        f"SDK `{versions['sdk']}` · native source `{versions['native']}` · charts `{versions['charts']}`.",
        "",
        f"{len(estimates)} registered estimator names; {len(replay['estimators'])} Dataset fitting routes; "
        f"{prediction['estimator_count']} common saved predict/margins adapters; "
        f"{prediction['remaining_estimator_count']} names without a common adapter.",
        "",
        "A registered route is implemented within its documented option and target domains. "
        "It does not establish unrestricted support, large-data performance on every model, "
        "or numerical parity. Shared prediction is distinct from family-specific forecasts and prediction helpers.",
        "",
        "## Status and evidence",
        "",
        "- **Implemented** means a registry or capability route exists; inspect its conditions below and in the JSON.",
        "- **Partial** means the documented supported domain has explicit exclusions; it is not blanket method coverage.",
        "- **Planned** methods in historical plans are not counted as implemented unless present in the registry.",
        "- **Parity tested** requires an identified external result and sample/options/inference comparison. "
        "The global `stata_parity_validated` flag remains `false`; selected independent or published-fixture tests do not change it.",
        "",
        "Selected validation modules: `tests/test_prediction_capabilities.py`, "
        "`tests/test_streaming_capability_conditions.py`, `tests/test_econ_core.py`, "
        "`tests/test_runtime_without_scipy.py`, `tests/test_capability_docs.py`. "
        "This inventory is not a test-run receipt; dated evidence records retain their original bounded scope.",
        "",
        "## Runtime, devices and dependencies",
        "",
        "Local source allocation guards and preparation contracts are published in the generated JSON "
        "and [Dataset preparation guide](dataset-preparation.md). Parser RSS, per-stage buffers, "
        "SQLite disk/cache and caller-function allocations have distinct scopes; pandas ordering, "
        "typed keys, missing tags and reshape policies are explicit.",
        "",
        f"Execution contract: {value['execution']}. Precision: `{value['precision']}`.",
        "",
        "Streaming device records: `" + json.dumps(replay["devices"], sort_keys=True) + "`.",
        "",
        replay["metal_precision"]
        + ". CUDA hardware validation remains "
        + (
            "recorded."
            if value["cuda_hardware_validated"]
            else "unverified in this source snapshot."
        ),
        "",
        "OpenEconometrics implements its estimators and separation certificates with native Torch kernels. "
        "SciPy, statsmodels and other reference estimators are development oracles, not required estimation engines. "
        "The frozen desktop packaging excludes SciPy. pandas, PyTorch and import/export dependencies retain "
        "NumPy dependencies; the environment is not NumPy-free. PyTorch may also bring NetworkX transitively; "
        "OpenEconometrics network algorithms do not use it as their analytical engine.",
        "",
        "Direct runtime declarations: `" + "`, `".join(value["dependencies"]["runtime"]) + "`.",
        "",
        "Development declarations: `" + "`, `".join(value["dependencies"]["dev_oracles"]) + "`.",
        "",
        "## Estimator support matrix",
        "",
        "| Estimator | Family | Dataset route | Common saved prediction | Covariance | Weights | Options |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for name, item in sorted(estimates.items()):
        weights = item.get("weights", [])
        if isinstance(weights, bool):
            weights = ["see core contract"] if weights else []
        fields = [
            f"`{name}`",
            item.get("family", "core"),
            "implemented" if name in replay["estimators"] else "unavailable",
            "conditional adapter"
            if name in prediction["estimators"]
            else "family-specific or planned",
            ", ".join(item["covariances"]),
            ", ".join(weights) or "none",
            ", ".join(sorted(item.get("options", {}))) or "see core contract",
        ]
        lines.append("| " + " | ".join(field.replace("|", "\\|") for field in fields) + " |")
    lines += [
        "",
        "## Dataset fitting conditions",
        "",
        f"Shared bounds: {replay['max_parameters']} parameters; no total row ceiling; "
        f"{replay['working_memory_budget_bytes']} bytes of planned working buffers. "
        "These are not total process RSS guarantees. Reader, disk, model width and repeated I/O constraints remain.",
        "",
    ]
    for name, algorithm in sorted(replay["algorithms"].items()):
        lines += [
            f"### `{name}`",
            "",
            algorithm + ".",
            "",
            "Conditions: `"
            + json.dumps(replay["conditions"].get(name, {}), sort_keys=True, ensure_ascii=False)
            + "`.",
            "",
        ]
    lines += [
        "## Common saved prediction",
        "",
        prediction["coverage_scope"] + ".",
        "",
        "Supported names: `" + "`, `".join(prediction["estimators"]) + "`.",
        "",
        "Remaining common adapters: `" + "`, `".join(prediction["remaining_estimators"]) + "`.",
        "",
        "Dataset evaluation requires explicit input and writes complete indexed output on disk. "
        "The stored 400-row fit/chart preview is separate from evaluation. Options such as panel FD, "
        "group effects, count cutoffs and multi-equation outcomes retain their explicit restrictions.",
        "",
        "See [prediction domains](econometrics/prediction-domains.md), "
        "[family coverage](econometrics/coverage.md) and [streaming contracts](streaming.md).",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source-ref")
    args = parser.parse_args()
    if args.check:
        if not JSON_PATH.exists() or not MD_PATH.exists():
            print("Capability documents missing. Run scripts/generate_capability_docs.py.")
            return 1
        reference = json.loads(JSON_PATH.read_text())["source_ref"]
    else:
        reference = (
            args.source_ref
            or subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
        )
    value = snapshot(reference)
    outputs = {
        JSON_PATH: json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        MD_PATH: markdown(value),
    }
    if args.check:
        changed = [
            (str(path.relative_to(ROOT)) if path.is_relative_to(ROOT) else str(path))
            for path, text in outputs.items()
            if path.read_text() != text
        ]
        if changed:
            print("Capability documentation drift: " + ", ".join(changed))
            return 1
        print("Capability documentation matches source.")
        return 0
    for path, text in outputs.items():
        path.write_text(text)
    print("Generated source-backed capability documents.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
